{:user {:plugins [[venantius/ultra "0.4.1"]
                  [com.jakemccrary/lein-test-refresh "0.14.0"]
                  [debugger "0.1.7" :exclusions [org.clojure/clojure]]
                  [lein-ancient "0.6.8"]
                  [lein-bin "0.3.5"]
                  [lein-typed "0.3.5"]
                  [org.clojure/core.typed "0.3.23" :exclusions [org.clojure/tools.reader]]
                  [jonase/eastwood "0.2.1" :exclusions [org.clojure/clojure]]
                  [jonase/kibit "0.1.2" :exclusions [org.clojure/clojure]]]
        :dependencies [[alembic "0.3.2"]
                       [acyclic/squiggly-clojure "0.1.3-SNAPSHOT"] ^:replace [org.clojure/tools.nrepl "0.2.12"]]}}
